# Generated by Django 5.2.7 on 2025-12-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conveyor_belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Item Name')),
                ('type', models.CharField(choices=[('s', 'solid'), ('l', 'liquid')], max_length=3, verbose_name='Item Type')),
                ('max_stack_size', models.IntegerField(verbose_name='Item Stack Size')),
                ('resource', models.BooleanField(default=False, verbose_name='Is Item Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Manipulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Items_In_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.FloatField(verbose_name='Quantity of Items Needed for Recipe')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items_DB.item')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Recipe Name')),
                ('time_to_complete', models.FloatField(verbose_name='Recipe Time to complete')),
                ('output_quantity', models.FloatField(verbose_name='Recipe Output Quantity')),
                ('items', models.ManyToManyField(through='Items_DB.Items_In_Recipe', to='Items_DB.item')),
            ],
        ),
        migrations.AddField(
            model_name='items_in_recipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items_DB.recipe'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Building Name')),
                ('speed', models.FloatField(verbose_name='Building Production Speed')),
                ('energy_source', models.CharField(choices=[('elc', 'electricity'), ('brn', 'burner')], max_length=3, verbose_name='Building Energy Source')),
                ('energy_consumption', models.FloatField(verbose_name='Building Energy Consumption')),
                ('energy_drain', models.FloatField(blank=True, verbose_name='Building Energy Drain')),
                ('pollution', models.FloatField(blank=True, verbose_name='Building Pollution')),
                ('n_of_module_slots', models.IntegerField(verbose_name='Building Module Slots')),
                ('productivity', models.FloatField(default=1, verbose_name='Building Productivity Rate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items_DB.item')),
                ('recipes', models.ManyToManyField(to='Items_DB.recipe')),
            ],
        ),
    ]
